class Elon
  def self.idea
    return [
      "An app that makes people act older.",
      "Telescopic salsa jars that get shorter as salsa decreases, thus allowing easier dipping of tortilla chips.",
      "Coffee shop that gives you extra strong drinks and a place to expel that energy called Caffeine and Trampoline.",
      "Blanket that absorbs and transfers heat from one person to another based on temperature preferences.",
      "Phone feature that rings your alarm just before the phone dies if you’ve set one for the morning and it is likely your power will run out before then.",
      "A channel that only plays The Simpsons reruns, but only the ones you watched from that very specific span of years when it was good.",
      "Electrified luggage carousel at airports that shocks anyone within 3 feet of their bag isn’t on said carousel.",
      "Conference call app that automatically mutes while you’re chewing or slurping.",
      "A diet that doesn’t involve you having to talk about it all the time.",
      "A display in airplanes that during turbulence lights up and reads, “Reminder: You’re fine. Not gonna die.”",
      "Self-driving dragon.",
      "A special glove that allows you to snap your fingers and eliminate half of movies with unoriginal plots.",
      "A version of PowerPoint that automatically compresses images because the majority of people who use the software don’t know how, or understand that emailing 30mb files is not super great.",
      "A designer French sock company called Sockré Bleu.",
      "Phone jammers built into the ground of all pedestrian crosswalks.",
      "A meal kit service center that lets you pick up a variety and exact amount of ingredients in one place and not have a ton of trash shipped to your doorstep.",
      "Eye tracking software that engages turn signals automatically when the driver (who has no regard for other humans and shouldn’t legally be allowed to be on the road or really be part of any modern society) doesn’t.
",
      "A dictionary, but a version where everyone agrees the words mean the same thing.",
      "Elevators that just vaporize anyone who tries walking in before people inside have stepped out, without exception.",
      "Routers that can handle 10,000 connections since your doormat and toilet brush are now smart devices for some reason.",
      "Bathroom doorknob that locks the door from inside if a certain level of bacteria is still detected on approaching hand.",
      "Email app that anonymously pings all your coworkers after New Year’s and then generates a report of who still has an out-of-office versus who is back.",
      "Self-imposed ads that run during tv shows you’re binging reminding you all of all the crap on your to-do list you’ve been putting off until holiday break.",
      "Cleaning service that preps your house before your cleaning person comes over.",
      "Table top board game where one person reads instructions for a new table top board game and the last person to not zone out is the winner.
",
      "TV that automatically changes text notification sounds in shows and commercials to something different than the one on your phone.",
      "Paper towels that are progressively thicker towards the bottom so when you pull one with your wet fingers you don’t just tear off a worthless tiny piece.
",
      "An online voting system where every citizen who wants to vote, just can.
",
      "EMP drone that flys over to a cell phone that has been left with the ringer on in an open office.
",
      "Service that matches you up with a body double who goes pants shopping for you.",
      "Fitted sheets company that lets you take a photo of your mattress, upload it, and then receive actual fitted sheets.",
      "Drones that produce artificial clouds around themselves and fly between you and the sun on extra hot days.",
      "Service that takes your unwanted items, slaps a Supreme sticker on them, then sells them on eBay to idiots for 100x their value.",
      "Music service that understands that skipping a song is effectively a thumbs down.",
      "App that comes up with an even more worthy cause when someone inputs something good they’re doing to help the world.
",
      "Tanning lotion with nano popcorn seeds mixed in. Starts popping and wakes you if you fall asleep in the sun too long.",
      "Glass doors that quickly become opaque when detecting someone is about to walk into it.",
      "Restaurant menus that remember you and highlight dishes you still haven’t ordered there.",
      "Coffee app that connects to a blood monitor and mobile orders for you when your caffeine rate dips below a certain level.",
      "Clothing hangers with digital displays that indicate how many days ago you wore an item.
",
      "Screens in elevators that play random YouTube clips timed to the length of your ride.",
      "Conference call service that recognizes your phone number and adds you to the proper room instead of making you type in 300 digits.",
      "An entire fake city where Instagram photographers and models can take photos and not be incredibly cringeworthy in front of people just waiting for a bus.",
      "Site that streams the opening to HBO’s Silicon Valley 24-7 and gets updated in real-time based on news.",
      "Dashboard indicator that lets you know when a car in front of the car you’re behind has their turn signal on.",
      "Podcast app that scans your brain waves and pauses audio when it knows you’re deep in thought and ignoring dialogue.",
      "Food delivery service that plans out your meals for the day after you step on a scale in the morning. Tentative name: Just Kale Me Now",
      "Vertical buildings that allow multiple people to live in one space instead of two million dollar shacks.",
      "A pie shop that sells slices that are exactly 90 degrees called “Pie-Thagorous.”",
      "Search engine that only displays sites that don’t block you from accessing content if you have Adblock installed.",
      "Door knobs that set off EMPs when turned by robots.",
      "LinkedIn filter that blocks users from posting on a certain subject unless they actually have X number of years experience in that subject on their profile.",
      "Algorithm that helps large companies pick an optimal city for a corporate office instead of running a publicity game show.
",
      "The Purge, except instead of one day a year of lawlessness, there’d be one day a year of balanced and well researched public policy debate.",
      "Chewable vitamins that have 5percent of the dosage so you can eat them like fruit-snacks.",
      "App that hears every time a store clerk asks if you’d like to donate a few dollars at checkout and instead donates it directly so YOU get the tax deduction.",
      "Drone that flies over to your coworkers desk to see if they’re there before you walk across the office to talk to them.",
      "Late night “go to sleep alarm” that makes your screens dimmer and dimmer until they’re totally black.",
      "Conference phones that automatically slide away from people who don't realize they speak at a deafening volume.",
      "App that unconnects you from your LinkedIn contacts if their job changes to “sales” or “growth.”
",
      "A pop-up Vietnamese restaurant that changes locations every week called, “New Pho Who Dis?”",
      "Email app that automatically adds smiley faces and exclamation points depending on the age or sensitivity of the recipient.",
      "Mobile browser that enlarges the impossibly tiny 'x' on pop-up ads.",
      "Drive thru restaurant that projects menu onto your windshield so you know what you want before pulling up to order.",
      "Secret AirBnB for people staying at their parents house who need to sneak out quietly to sleep in a comfortable bed.",
      "Guns that email notifications to the seller and manufacturer each time the weapon has killed someone.",
      "Blanket that temporarily stiffens in appropriate spots so your dog can walk on you in the morning and not wake you up.
",
      "Airline where every pilot is a working stand-up comic. Does their act during the flight.",
      "Email app that holds all messages sent after 3pm on Friday and sends them to you on Monday morning. So you actually read them.",
      "Dishwasher that scans dirty items and directs focus of water accordingly.",
      "App that automatically updates all your recurring credit card payments after yours inevitably gets compromised every damn year.",
      "A crypto currency in which being an early adopter is not an enormous benefit.",
      "Airplane speakers that mute safety announcements for anyone that has TSA pre-check.",
      "VR game that drops you into a fantasy world where people actually want to use VR.",
      "Email app for your parents that does not come loaded with a forwarding feature.",
      "Trash bin that sucks up crumpled up pieces of paper nearby because you missed that epic basketball shot.
",
      "Fidget spinner that connects to and disables your phone while it's spinning thus solving the real problem.",
      "AI bot that answers telemarketing calls for you and has long, seemingly plausible conversations to waste as much time as possible.",
      "Podcast app that connects to Google Maps and finds you a perfectly timed episode based on your commute.",
      "Bathroom motion sensor lights that actually know the difference between someone not being in the room, and someone sitting still.",
      "Alarm that also starts a timer for how long you're allowed to f*** around on your phone after waking up.",
      "Thermostat that sets your entire house to be the same temperate as under your blanket as you wake up and get out of bed.",
      "App that turns on airplane mode when it detects a flight attendant within 6 feet.",
      "Email app that recognizes you're trying to download an attachment you already have and instead just opens it for you."
    ].sample
  end
end
